### ISSUE TITLE
Publish the repository as a nuget package

### ISSUE THREAD

**Issue by duongntbk** [mdsol/FastAndFaster#2]
Hi,
I just wondering if it is possible to publish this repository as a nuget package?
I believe that will make this repo much more easier to use.

**Comment by prajon84** [comment]
Hello @duongntbk  
 I think to publish as nuget package in "nuget.org",  some team needs to own this repo and take care of publishing this repo when there is changes to "nuget.org" via "mdsol credentials" similar to how we publish "mauth-client-dotnet" public repo into "nuget.org"

cc: @jfeltesse-mdsol @hkurniawan-mdsol @bflanaghan-mdsol

**Comment by hkurniawan-mdsol** [comment]
Currently asking infosec for the nuget credentials.
We'll keep you posted.

**Comment by hkurniawan-mdsol** [comment]
@duongntbk 
As you mentioned it here, https://github.com/mdsol/FastAndFaster/pull/6#event-7664737429, it's best that if you fork this repo and take full control of it.

Sorry we couldn't give you a better solution.
All the best on your OSS adventure.

We will be archiving this repo in the coming days.
