### ISSUE TITLE
Allow the general public to access the blog post at the top of README file 

### ISSUE THREAD

**Issue by duongntbk** [mdsol/FastAndFaster#3]
Hi,
Currently [this](https://dsext001-eu1-215dsi0708-ifwe.3dexperience.3ds.com///#app:X3DMCTY_AP/content:url=https%3A%2F%2Fdsext001-eu1-215dsi0708-3dswym%2e3dexperience%2e3ds%2ecom&community=k-qK1CFpS2qhQzhlwrAHIw&contentType=post&contentId=ALBm1I_8RXaejD35x2K9Jw) link at the top of the [README.md](https://github.com/mdsol/FastAndFaster/blob/1f3fa653e35f6cd60f327069ca286c5a94becdf3/README.md) is not accessible for the general public.
Can we make it public?

**Comment by prajon84** [comment]
@duongntbk : That link points to 3DS blog post and I do not think 3DS is accessible only to 3DS employees.
Therefore, you need to move that blog post or re-write in publicly accessible area and add that link.

**Comment by duongntbk** [comment]
New PR opened https://github.com/mdsol/FastAndFaster/pull/7.
